name: goofy_converter
description: A weird Goofy unit converter app written on Flutter/Dart.
version: 0.0.1+1
authors:
  - Maxeem (America) Shemetov <maxeem.america@gmail.com>
repository: https://github.com/maxeema/flutter-goofy-converter

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  cupertino_icons: ^0.1.2

  shared_preferences: ^0.5.3
  package_info: ^0.4.0+6
  flutter_svg: ^0.14.1
  url_launcher: ^5.1.4
  fluttertoast: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/goofy_units.json
    - assets/icons/app_icon.svg
    - assets/icons/area.svg
    - assets/icons/currency.svg
    - assets/icons/digital.svg
    - assets/icons/length.svg
    - assets/icons/mass.svg
    - assets/icons/energy.svg
    - assets/icons/time.svg
    - assets/icons/volume.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-ExtraLight.ttf
          weight: 200
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
