name: converter
description: Converter is a unit converter app written on Flutter
version: 0.5.3+3
authors:
  - iMax Shemetov <imax.shemetov@gmail.com>
repository: https://github.com/maxeema/converter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.9.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  cupertino_icons: ^0.1.3

  package_info: ^0.4.3
#  flutter_svg: ^0.18.0
  url_launcher: ^5.5.0
  fluttertoast: ^7.0.2
  websafe_svg: ^1.1.4
  get_it: any

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon.png
    - assets/data/
    - assets/icons/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-ExtraLight.ttf
          weight: 200
