name: converter
description: Converter is a unit converter app written on Flutter
version: 0.6.12+12
authors:
  - Max Shemetov <shemetov.career@gmail.com>
repository: https://github.com/maxeema/converter
publish_to: 'none'

environment:
  sdk: ">=2.9.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: any
  cupertino_icons: any

  package_info: any
  url_launcher: any
  fluttertoast: any
  websafe_svg: any
  flutter_hooks: any
  get_it: any
#  google_fonts: any

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon.png
    - assets/data/
    - assets/icons/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-ExtraLight.ttf
          weight: 200
